name: spookify_v2
description: "Spotify Copy project connected to Spotify Web Api."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dartz: ^0.10.1
  dio: ^5.7.0
  either_dart: ^1.0.0
  equatable: ^2.0.7
  floor: ^1.5.0
 
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_spinkit: ^5.2.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.6.3
  http: ^1.2.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.5
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  floor_generator: ^1.5.0
  single_import_generator: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic

    - family: CircularSpotify
      fonts:
        - asset: assets/fonts/CircularSpotifyText-Book.otf
        - asset: assets/fonts/CircularSpotifyText-Bold.otf
          weight: 700
      
